Repository develop-me/bagajob, pull requests merged in 2020-09, with the labels that each got.

#47 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#52 removed /bagajob from homepage URL
  package.json
Labels: bug

#42 User account page and auth functionality
  example.json
  package-lock.json
  package.json
  src/components.html
  src/components/Account/Account.js
  src/components/Account/AccountDetail.js
  src/components/Account/AccountHeader.js
  src/components/App.js
  src/components/AuthForms/ForgotPassword.js
  src/components/AuthForms/Login.js
  src/components/AuthForms/Logout.js
  src/components/AuthForms/PasswordReset.js
  src/components/AuthForms/SignUp.js
  src/components/FourOhFour.js
  src/components/Home.js
  src/components/Job/ApplicationCard/ApplicationInput.js
  src/components/Job/ApplicationCard/ApplicationNote.js
  src/components/Job/ApplicationCard/index.js
  src/components/Job/InterviewCard/Interview.js
  src/components/Job/InterviewCard/index.js
  src/components/Job/Job.js
  src/components/Job/JobDetailsCard/JobDetail.js
  src/components/Job/JobDetailsCard/index.js
  src/components/JobForms/JobForms.js
  src/components/Loading.js
  src/components/MainPage/MainPage.js
  src/components/Nav.js
  src/components/PrivateRoute.js
  src/css/styles.min.css
  src/css/styles.min.css.map
  src/customHooks/useFormValidation.js
  src/data/Account/actions.js
  src/data/Account/constants.js
  src/data/Account/reducer.js
  src/data/ApiRequests/account.js
  src/data/ApiRequests/appNotes.js
  src/data/ApiRequests/auth.js
  src/data/ApiRequests/interviews.js
  src/data/ApiRequests/jobs.js
  src/data/AppNotes/actions.js
  src/data/AppNotes/constants.js
  src/data/AppNotes/reducer.js
  src/data/Auth/actions.js
  src/data/Auth/constants.js
  src/data/Auth/reducer.js
  src/data/Interviews/actions.js
  src/data/Interviews/constants.js
  src/data/Interviews/reducer.js
  src/data/Jobs/actions.js
  src/data/Jobs/constants.js
  src/data/Jobs/reducer.js
  src/data/RootReducer.js
  src/data/store.js
  src/helpers/validateAuth.js
  src/scss/main.scss
  src/scss/organisms/_nav.scss
  src/scss/templates/_app.scss
Labels: enhancement
